import type { Metadata } from "next";
import Image from "next/image";

import compromiso from "@/img/compromiso.jpg";

import { MusicToggle } from "@/components/landing/MusicToggle";
import { SaveTheDate } from "@/components/landing/SaveTheDate";
import { COUPLE_NAMES, formatWeddingDate } from "@/lib/domain/wedding-day";

/**
 * The public save-the-date.
 *
 * THIS IS NOT THE INVITATION AND IT MUST NEVER BECOME ONE.
 *
 * `/` is public and indexable. It carries the couple, the day and a countdown —
 * nothing else. No guest name, no address, no phone number, no RSVP: those live
 * at `/i/[slug]` behind the phone gate, and `app/robots.ts` keeps that prefix
 * out of every search index precisely because an invitation URL is an unlisted
 * capability. Adding a venue or a stream credential to this file would move a
 * private fact onto a page anyone can find.
 *
 * The route composes and does not decide. All copy lives in `SaveTheDate`; the
 * only thing this file owns is the photograph, the scrim over it, and where the
 * two blocks sit on top.
 */

/** Served from `public/`, which is the only folder Next serves verbatim. */
const SONG_SRC = "/audio/nuestra-cancion.mp3";

/**
 * What a crawler and a WhatsApp preview see.
 *
 * `metadataBase` is set once in `app/layout.tsx`, so the relative image path
 * below resolves to an absolute HTTPS URL. Without it the emitted `og:image`
 * stays relative and no external crawler can fetch it — the same trap the
 * per-guest card at `/i/[slug]/opengraph-image.tsx` already documents.
 *
 * `compromiso.src` rather than a written path: the static import is
 * content-hashed at build time, so a literal would break on the first change to
 * the photograph and would do it silently, in the preview card only.
 */
const TITLE = `${COUPLE_NAMES} — ${formatWeddingDate()}`;
const DESCRIPTION = "Nos casamos, y queremos celebrarlo con ustedes.";

export const metadata: Metadata = {
  title: TITLE,
  description: DESCRIPTION,
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: "website",
    locale: "es_CO",
    images: [
      {
        url: compromiso.src,
        width: compromiso.width,
        height: compromiso.height,
        alt: `${COUPLE_NAMES}, tomados de la mano frente a una cascada`,
      },
    ],
  },
};

export default function Home() {
  return (
    /*
     * `min-h-dvh`, not `min-h-screen`. On a phone `100vh` is the viewport with
     * the browser chrome HIDDEN, so a full-height hero is taller than what is
     * actually on screen and the countdown sits under the address bar until the
     * visitor scrolls. `dvh` tracks the chrome as it collapses.
     *
     * The background colour is the photograph's own darkness. It is what fills
     * the frame for the instant before the image decodes, so the page never
     * flashes white — on a hero this dark, white is the only visible failure.
     */
    <main className="relative min-h-dvh overflow-hidden bg-[#0d1114]">
      <Image
        src={compromiso}
        alt="Luis y Michell abrazados en un sendero, con una cascada iluminada detrás"
        fill
        /*
         * `preload`, NOT `priority`. `priority` is deprecated as of Next 16
         * (see the `image` API reference, "Version History", v16.0.0); this is
         * the LCP element, so it is preloaded from the `<head>` rather than
         * discovered later in the body.
         */
        preload
        /*
         * Generated by the static import at build time. On a photograph this
         * dark the blur-up is not decoration — it is what makes the frame look
         * deliberate for the few hundred milliseconds before the real pixels
         * land.
         */
        placeholder="blur"
        sizes="100vw"
        /*
         * `object-fit` is NOT a prop — it was removed in Next 13 — so the crop
         * is a utility class.
         *
         * MEASURED, NOT GUESSED. The photograph is 737×1600 (0.46:1) and a
         * 16:9 window is 1.78:1, so `cover` scales it by width and shows only
         * 26% of its height — a narrow horizontal band. Centred, that band
         * lands on the waterfall; at 58% it landed on the couple's faces and
         * the heading below sat on their chins.
         *
         * 66% puts the window at 53%–79% of the photograph: the two of them
         * near the top of the frame, their legs and the path underneath, and
         * the text block over the path rather than over them.
         *
         * A phone changes nothing here. At 390×844 the viewport is 0.462:1 —
         * the photograph's own ratio to three decimals — so `cover` shows all
         * of it and the position has nothing left to choose.
         */
        className="object-cover object-[center_66%]"
      />

      {/*
        TWO SCRIMS, ONE PER BAND OF TEXT, AND THAT IS NOT AN EXTRA DIV FOR ITS
        OWN SAKE.

        A single top-to-bottom gradient has to be dark at both ends and clear in
        the middle, which is exactly wrong on a wide screen: there, the whole
        visible crop IS the middle, so the text ended up carried by its own
        shadow alone. Each band now gets a scrim sized to itself, and the couple
        — who sit between them — stay unclouded on every viewport.

        The bottom one is the taller and the darker of the two because it
        carries the heading, the date and four figures; the top one only has to
        hold two words.
      */}
      <div
        aria-hidden="true"
        className="absolute inset-x-0 top-0 h-1/4 bg-gradient-to-b from-black/70 to-transparent"
      />
      <div
        aria-hidden="true"
        className="absolute inset-x-0 bottom-0 h-3/5 bg-gradient-to-t from-black/90 via-black/55 to-transparent"
      />

      <div className="relative flex min-h-dvh flex-col items-center justify-between gap-12 px-6 pt-10 pb-[max(3rem,env(safe-area-inset-bottom))] sm:pt-14 sm:pb-14">
        <p
          className="
            font-script text-3xl text-[#f6efe2]/90
            [text-shadow:0_1px_14px_rgba(0,0,0,0.6)]
            sm:text-4xl
          "
        >
          Nos casamos
        </p>

        <SaveTheDate />
      </div>

      {/*
        TOP RIGHT, BECAUSE BOTTOM RIGHT COLLIDED.

        It sat in the bottom corner first and overlapped the word "segundos" on
        a 390px phone — the countdown is four columns wide and the last one ends
        exactly where a 44px control in that corner begins. The top band holds
        one centred line of script and has room to spare on both sides.

        `fixed` rather than `absolute` so it stays reachable if this page ever
        grows past one screen. The inset respects the notch.
      */}
      <div className="fixed top-[max(1.25rem,env(safe-area-inset-top))] right-5 z-10">
        <MusicToggle src={SONG_SRC} />
      </div>
    </main>
  );
}
