import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { globSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { CONSOLE_BREAKPOINT_VARIANT } from "@/lib/design/console-nav";

/**
 * ONE BREAKPOINT IN THE CONSOLE. THIS IS THE TEST THAT KEEPS IT AT ONE.
 *
 * A reference console flipped its table layout at 600px and its navigation at
 * 900px. Between those widths — every tablet, every landscape phone, every
 * half-width desktop window — it rendered a phone tab bar underneath a six-column
 * desktop table. Nobody designed that; it fell out of two independent decisions
 * made months apart.
 *
 * A comment saying "one breakpoint" survives exactly until the first screen that
 * would look slightly better with a second one. Reading the sources does not.
 *
 * `components/ui/**` is EXEMPT: those files are vendored from the shadcn registry
 * and are re-generated by `npx shadcn@latest add`. Rewriting their internal
 * breakpoints would be undone by the next regeneration, and they are primitives
 * rather than console layout.
 */

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

const CONSOLE_SOURCES = [
  ...globSync("components/console/**/*.tsx", { cwd: REPO_ROOT }),
  ...globSync("app/console/**/*.tsx", { cwd: REPO_ROOT }),
].filter((file) => !file.endsWith(".spec.tsx"));

/** Every Tailwind responsive variant prefix, in the order they widen. */
const RESPONSIVE_VARIANTS = ["sm", "md", "lg", "xl", "2xl"] as const;

/** The responsive variants one file uses, deduplicated. */
function variantsUsedIn(file: string): readonly string[] {
  const source = readFileSync(`${REPO_ROOT}${file}`, "utf8");
  const used = RESPONSIVE_VARIANTS.filter((variant) =>
    // `"md:` or ` md:` — a class-list position, not a substring of a word.
    new RegExp(`[\\s"'\`:\\[]${variant}:`).test(source),
  );

  return used;
}

describe("the console changes shape at exactly one width", () => {
  it("has console sources to check, so this file is not vacuously green", () => {
    expect(CONSOLE_SOURCES.length).toBeGreaterThanOrEqual(5);
  });

  it.each(CONSOLE_SOURCES)("%s uses no other breakpoint", (file) => {
    const offending = variantsUsedIn(file).filter(
      (variant) => variant !== CONSOLE_BREAKPOINT_VARIANT,
    );

    expect(offending).toEqual([]);
  });

  it("does use the one breakpoint somewhere, or the shell never changes shape", () => {
    const usesTheBreakpoint = CONSOLE_SOURCES.some((file) =>
      variantsUsedIn(file).includes(CONSOLE_BREAKPOINT_VARIANT),
    );

    expect(usesTheBreakpoint).toBe(true);
  });
});
